name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: print greeting
        run: echo "Hello World!"
      - name: print goodbye
        run: echo "Done - bye!"
      - name: Run multi-Line Shell commnds
        run: |
          echo "First output"
          echo "Second output"

